export const COURSE_LEVELS = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
} as const

export const COURSE_LEVEL_LABELS = {
  [COURSE_LEVELS.BEGINNER]: '入门',
  [COURSE_LEVELS.INTERMEDIATE]: '进阶',
  [COURSE_LEVELS.ADVANCED]: '高级',
} 